version: '3.8'

services:
  # Accounts Service
  accounts-service:
    build: .
    container_name: accounts-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - VAULT_TOKEN=dev-token
      - JWT_SECRET=devjwtsecretdevjwtsecretdevjwtsecretdevjwtsecret
    depends_on:
      - postgres
      - redis
      - kafka
      - zookeeper

  # PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: accounts-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounts_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:alpine
    container_name: accounts-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: accounts-zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: accounts-kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: accounts-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: accounts-grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  postgres-data:
  redis-data:
  prometheus-data:
  grafana-data:
